//! Blue noise sampler for spatially-uniform error distribution.
//!
//! Uses a precomputed 256x256 blue noise texture with Cranley-Patterson
//! rotation for temporal decorrelation across progressive passes.
//! Produces better denoiser input than white noise.
//!
//! Texture generated by `scripts/gen_blue_noise.py` (void-and-cluster algorithm).

/// Blue noise texture size (256x256 = 65,536 bytes).
const TEXTURE_SIZE: u32 = 256;

/// Golden ratio fractional part for Cranley-Patterson rotation (X dimension).
const PHI: f32 = 0.618_034;

/// Second irrational for Y dimension temporal rotation (fract(sqrt(2))).
/// Using a different constant decorrelates X/Y temporal movement.
const PHI2: f32 = 0.414_214;

/// Embedded 256x256 blue noise texture (void-and-cluster).
static BLUE_NOISE: &[u8; (TEXTURE_SIZE * TEXTURE_SIZE) as usize] =
    include_bytes!("data/blue_noise_256x256.bin");

/// Sampler mode for camera jitter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum SamplerMode {
    /// Standard white noise RNG (traditional).
    WhiteNoise,
    /// Blue noise texture with Cranley-Patterson rotation (better for denoising).
    #[default]
    BlueNoise,
}

impl SamplerMode {
    /// Display name for UI.
    pub fn display_name(&self) -> &'static str {
        match self {
            SamplerMode::WhiteNoise => "White Noise",
            SamplerMode::BlueNoise => "Blue Noise",
        }
    }

    /// All variants for UI dropdown.
    pub fn all() -> &'static [SamplerMode] {
        &[SamplerMode::WhiteNoise, SamplerMode::BlueNoise]
    }
}

/// Sample a 2D blue noise value for a pixel, decorrelated across samples.
///
/// Returns (x, y) in [0, 1) suitable for sub-pixel jitter. Uses Cranley-Patterson
/// rotation to ensure each sample index produces a different value while
/// maintaining the blue noise spatial distribution.
///
/// `sample_index` is the temporal decorrelation key — use `pass_number + sample_offset`
/// so both progressive passes and multi-SPP within a pass get unique jitter.
///
/// The second dimension uses a fixed spatial offset (37, 71) into the texture
/// and a different irrational (fract(sqrt(2))) for temporal rotation to
/// decorrelate X/Y movement.
pub fn sample_2d(pixel_x: u32, pixel_y: u32, sample_index: u32) -> (f32, f32) {
    // First dimension: direct texture lookup
    let tx = pixel_x % TEXTURE_SIZE;
    let ty = pixel_y % TEXTURE_SIZE;
    let raw_x = BLUE_NOISE[(ty * TEXTURE_SIZE + tx) as usize] as f32 / 256.0;

    // Second dimension: offset texture coords to decorrelate
    let tx2 = (pixel_x + 37) % TEXTURE_SIZE;
    let ty2 = (pixel_y + 71) % TEXTURE_SIZE;
    let raw_y = BLUE_NOISE[(ty2 * TEXTURE_SIZE + tx2) as usize] as f32 / 256.0;

    // Cranley-Patterson rotation with different irrationals per dimension
    let x = fract(raw_x + PHI * sample_index as f32);
    let y = fract(raw_y + PHI2 * sample_index as f32);

    (x, y)
}

/// Fractional part of a float, always in [0, 1).
#[inline]
fn fract(x: f32) -> f32 {
    x - x.floor()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sample_range() {
        // All outputs must be in [0, 1)
        for pass in 0..100 {
            for px in 0..260 {
                for py in 0..3 {
                    let (x, y) = sample_2d(px, py, pass);
                    assert!(
                        (0.0..1.0).contains(&x),
                        "x={x} out of range at px={px}, py={py}, pass={pass}"
                    );
                    assert!(
                        (0.0..1.0).contains(&y),
                        "y={y} out of range at px={px}, py={py}, pass={pass}"
                    );
                }
            }
        }
    }

    #[test]
    fn test_different_passes_different_values() {
        let (x0, y0) = sample_2d(50, 50, 0);
        let (x1, y1) = sample_2d(50, 50, 1);
        let (x2, y2) = sample_2d(50, 50, 2);

        // Different passes must produce different values (Cranley-Patterson)
        assert_ne!(x0, x1, "pass 0 and 1 should differ in x");
        assert_ne!(x1, x2, "pass 1 and 2 should differ in x");
        assert_ne!(y0, y1, "pass 0 and 1 should differ in y");
    }

    #[test]
    fn test_tiling() {
        // Texture tiles at 256 boundary
        let (x0, y0) = sample_2d(10, 20, 5);
        let (x1, y1) = sample_2d(10 + TEXTURE_SIZE, 20 + TEXTURE_SIZE, 5);
        assert_eq!(x0, x1, "should tile in x");
        assert_eq!(y0, y1, "should tile in y");
    }

    #[test]
    fn test_decorrelated_xy() {
        // X and Y dimensions should be different (offset lookup + different rotation)
        let mut same_count = 0;
        for px in 0..64 {
            for py in 0..64 {
                let (x, y) = sample_2d(px, py, 0);
                if (x - y).abs() < 1e-6 {
                    same_count += 1;
                }
            }
        }
        // With 4096 samples, very few should coincide
        assert!(
            same_count < 100,
            "too many coincident x/y values: {same_count}"
        );
    }

    #[test]
    fn test_xy_temporal_decorrelation() {
        // X and Y should move independently across passes (different irrationals)
        let (x0, _y0) = sample_2d(100, 100, 0);
        let (x1, _y1) = sample_2d(100, 100, 1);
        let (x2, y2) = sample_2d(100, 100, 2);
        let (x3, y3) = sample_2d(100, 100, 3);

        // X moves by PHI per pass, Y by PHI2 — deltas should differ
        let dx = fract(x1 - x0 + 1.0);
        let dy = fract(_y1 - _y0 + 1.0);
        assert!(
            (dx - dy).abs() > 0.01,
            "X/Y should use different rotation: dx={dx}, dy={dy}"
        );

        // Multi-pass should not repeat within reasonable range
        assert_ne!((x2, y2), (x3, y3), "consecutive samples should differ");
    }
}
