// Phase 0 spike app_main — C++ side orchestrates QApplication,
// QMainWindow, and the RenderWidget + signal wiring. Rust main()
// calls qt_spike_run() with a pointer to Rust-owned SpikeCallbacks.
//
// The function is generated by cxx as `extern "C"` (declared in the
// cxx bridge at src/bridge.rs) — this header is included by the
// generated C++ glue.

#pragma once

// Forward-declared by the cxx-generated bridge header.
struct SpikeCallbacks;

// Entry point called from Rust fn main. Blocks until QApplication's
// event loop exits. argc/argv are constructed internally.
int qt_spike_run(SpikeCallbacks* callbacks);
