[package]
name = "bif_math"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
glam = { workspace = true }
bytemuck = { workspace = true }
serde = { workspace = true }
log = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
