[package]
name = "bif_perf"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "bif_perf"
path = "src/main.rs"

[dependencies]
bif_core = { path = "../crates/bif_core" }
clap = { version = "4", features = ["derive"] }
serde = { workspace = true }
serde_yml = "0.0.12"
tabled = "0.17"
log = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
